name: xmed
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  connectivity_plus: ^4.0.1
  google_fonts: ^5.1.0
  form_builder_validators: ^9.0.0
  floating_snackbar: ^1.0.3+1
  path_provider: ^2.1.0
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  dio: ^4.0.6
  flutter_dotenv: ^5.1.0
  fast_rsa: ^3.5.7
  pem: ^2.0.4
  pointycastle: ^3.7.3
  rsa_encrypt: ^2.0.0
  auto_route: ^7.8.0
  oktoast: ^3.3.1
  dartz: ^0.10.1
  dio_logging_interceptor: ^1.0.1
  flutter_secure_storage: ^8.0.0
  http: ^1.1.0
  side_navigation: ^1.0.4
  settings_ui: ^2.0.2
  intl: ^0.18.0
  pdf: ^3.10.4
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  auto_route_generator: ^7.3.1





flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env.test
    - packages/fast_rsa/web/assets/worker.js
    - packages/fast_rsa/web/assets/wasm_exec.js
    - packages/fast_rsa/web/assets/rsa.wasm

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
